--
--INSERT INTO employee.self_service_type(self_service_type_name) VALUES('Complain');
--INSERT INTO employee.self_service_type(self_service_type_name) VALUES('Request');
--INSERT INTO employee.self_service_type(self_service_type_name) VALUES('Feedback');
--
--INSERT INTO employee.department(department_name) VALUES('hrm');
--INSERT INTO employee.department(department_name) VALUES('manager');
